[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
verbosity = 3

[fuzz]
max_test_rejects = 1_000_000 # Number of times `vm.assume` can fail

[rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
arbitrum = "https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true
